---
before_install:
  - rm Gemfile.lock
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
