version: 2
jobs:
  build:
    docker:
      - image: docker:git

    working_directory: /usr/src/app

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/docker-image.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/docker-image.tar | true
      - run:
          name: Build app Docker image
          command: |
            docker build --cache-from=ruby-enc -t ruby-enc --build-arg BUNDLE_GEM__FURY__IO=$BUNDLE_GEM__FURY__IO .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/docker-image.tar ruby-enc
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/docker-image.tar
      - run:
          name: Build and upload gem
          command: |
            docker run \
            -e CIRCLE_BRANCH=${CIRCLE_BRANCH} \
            -e CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM} \
            -e BUNDLE_GEM__FURY__IO=${BUNDLE_GEM__FURY__IO} \
            -e MAJOR_VERSION=${MAJOR_VERSION} \
            -e MINOR_VERSION=${MINOR_VERSION} \
            -it ruby-enc bin/build.sh