sqlite: &sqlite3
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql2
  adapter: mysql2
  username: root
  password:
  database: enc_<%= Rails.env %>

postgresql: &pg
  adapter: postgresql
  username: postgres
  password:
  database: enc_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 16
  timeout: 5000
  <<: *<%= ENV['DB'] || "mysql2" %>

development:
  adapter: mysql2
  encoding: utf8
  host: enc-dashboard.c1phlpd5jvwq.us-west-2.rds.amazonaws.com
  port: 3306
  database: dashboard_development
  username: dashboard
  password: d4aca968

test:
  <<: *defaults
  host: localhost

production:
  # <<: *defaults
  # presumably, we'd erb-echo the production password from /etc/something here.
  adapter: mysql2
  encoding: utf8
  host: enc-dashboard
  database: dashboard_production
  username: dashboard
  password: d4aca968
